
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 21;
  public static final int UNDERSCORE = 31;
  public static final int AND = 23;
  public static final int RETURN_SIGN = 13;
  public static final int RAB = 11;
  public static final int PLUS = 17;
  public static final int INT = 24;
  public static final int OR = 22;
  public static final int EQUAL = 29;
  public static final int LP = 14;
  public static final int CHAR = 25;
  public static final int RP = 15;
  public static final int NOT_EQUAL = 30;
  public static final int ID = 8;
  public static final int STRING = 28;
  public static final int COMMA = 16;
  public static final int FLOAT = 27;
  public static final int EOF = 0;
  public static final int MAIN = 4;
  public static final int DIV = 20;
  public static final int MINUS = 18;
  public static final int CONST = 9;
  public static final int CASE = 7;
  public static final int error = 1;
  public static final int ASSIGN = 12;
  public static final int LAB = 10;
  public static final int BOOL = 26;
  public static final int DEFAULT = 6;
  public static final int FRANJO = 2;
  public static final int MUL = 19;
  public static final int DECLARE = 5;
  public static final int TUDJMAN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FRANJO",
  "TUDJMAN",
  "MAIN",
  "DECLARE",
  "DEFAULT",
  "CASE",
  "ID",
  "CONST",
  "LAB",
  "RAB",
  "ASSIGN",
  "RETURN_SIGN",
  "LP",
  "RP",
  "COMMA",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "OR",
  "AND",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "STRING",
  "EQUAL",
  "NOT_EQUAL",
  "UNDERSCORE"
  };
}

